name: Java CI with Maven Arrange

on:
  push:
    branches: [Arranege]
  pull_request:
    branches: [Arrange]

jobs:
  build:
    name: Start Buiding 
    runs-on: ubuntu-latest

    steps:
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Build JHotDraw with Maven
      run: mvn -B package --file ./JHotDraw/pom.xml
      # Runs a set of commands using the runners shell